name: Auto Update and Build

on:
  workflow_dispatch:


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current version from Docker Hub
        id: version
        run: |
          IMAGE="pmoscode/excalidraw-collab-server"
          CURRENT_VERSION=$(curl -s https://hub.docker.com/v2/repositories/$IMAGE/tags?page_size=100 | jq -r '.results[].name' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
          
          if [ -z "$CURRENT_VERSION" ]; then
            CURRENT_VERSION="1.0.0"
          fi
          
          echo "Current version: $CURRENT_VERSION"
          
          PATCH=$(echo $CURRENT_VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          
          echo "NEW_VERSION=$PATCH" >> $GITHUB_ENV
          echo "New version: $PATCH"

      - name: Build and push new Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            pmoscode/excalidraw-collab-server:${{ steps.version.outputs.NEW_VERSION }}
            pmoscode/excalidraw-collab-server:latest
